services:
  - type: web
    name: para-sports-frontend
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: "./dist"
    envVars:
      - key: VITE_API_URL
        value: https://your-backend-service.onrender.com
    routes:
      - path: /*
        staticWebApp: true  # Serves index.html for all routes